src/Entity/AppUser.php
<?php

namespace App\Entity;

use App\Repository\AppUserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Uid\Uuid;

/**
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Entity(repositoryClass=AppUserRepository::class)
 */
class AppUser implements UserInterface
{
    public function __construct()
    {
        $this->username = uniqid("user_");
        $this->uuid = (Uuid::v4())->toRfc4122();
        $this->setAsNeverExpireUser();
        $this->referralCode = substr(str_shuffle("0123456789ABCDEFGHIJKLMNOPQRSDUVWXYZabcdefghijklmnopqrstuvwxyz"), 0, 7);
    }

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="bigint")
     */
    private int $id;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @ORM\Column(type="string", unique=true)
     * @var string
     */
    private string $uuid;

    /**
     * @param string $uuid
     * @return $this
     */
    public function setUuid(string $uuid) : self
    {
        $this->uuid = $uuid;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getUuid() : ?string
    {
        return $this->uuid;
    }

    /**
     * @ORM\Column(type="string", unique=true)
     * @var string $username
     */
    private string $username;

    /**
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * @param string $username
     * @return $this
     */
    public function setUsername(string $username) : self
    {
        $this->username = $username;
        return $this;
    }

    /**
     * @ORM\Column(type="string", unique=true, nullable=true)
     * @var string|null $email
     */
    private ?string $email;

    /**
     * @param string $email
     * @return $this
     */
    public function setEmail(?string $email) : self
    {
        $this->email = $email;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getEmail() : ?string
    {
        return $this->email;
    }

    /**
     * @ORM\Column(type="boolean", name="is_email_verified", options={"default": false})
     * @var bool $emailVerified
     */
    private bool $emailVerified = false;

    /**
     * @param bool $emailVerified
     * @return $this
     */
    public function setEmailVerified(bool $emailVerified) : self
    {
        $this->emailVerified = $emailVerified;
        return $this;
    }

    /**
     * @return bool
     */
    public function isEmailVerified() : bool
    {
        return $this->emailVerified;
    }

    /**
     * @ORM\Column(type="string", nullable=true)
     * @var string $passwordHash
     */
    private string $passwordHash;

    /**
     * @param string $passwordHash
     * @return $this
     */
    public function setPasswordHash(string $passwordHash) : self
    {
        $this->passwordHash = $passwordHash;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getPassword() : ?string
    {
        return $this->passwordHash;
    }

    /**
     * @return string|null
     */
    public function getPasswordHash() : ?string
    {
        return $this->passwordHash;
    }

    /**
     * Other unique data
     */

    /**
     * @var string|null $mobile
     * @ORM\Column(type="string", unique=true, nullable=true)
     */
    private ?string $mobile;

    /**
     * @param string $mobile
     * @return $this
     */
    public function setMobile(?string $mobile) : self
    {
        $this->mobile = $mobile ?? null;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getMobile() : ?string
    {
        return $this->mobile;
    }

    /**
     * @var bool $mobileVerified
     * @ORM\Column(type="boolean", name="is_mobile_verified", options={"default": false})
     */
    private bool $mobileVerified = false;

    /**
     * @param bool $mobileVerified
     * @return $this
     */
    public function setMobileVerified(bool $mobileVerified) : self
    {
        $this->mobileVerified = $mobileVerified;
        return $this;
    }

    /**
     * @return bool
     */
    public function isMobileVerified() : bool
    {
        return $this->mobileVerified;
    }

    /**
     * @ORM\Column(type="string", unique=true, nullable=true)
     * @var string|null $facebookId
     */
    private ?string $facebookId;

    /**
     * @param string|null $facebookId
     * @return $this
     */
    public function setFacebookId(?string $facebookId) : self
    {
        $this->facebookId = $facebookId;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getFacebookId() : ?string
    {
        return $this->facebookId;
    }

    /**
     * @ORM\Column(type="string", nullable=true, unique=true)
     * @var string|null
     */
    private ?string $googleId;

    public function setGoogleId(?string $googleId) : self
    {
        $this->googleId = $googleId ?? "";
        return $this;
    }

    /**
     * @return string|null
     */
    public function getGoogleId() : ?string
    {
        return $this->googleId;
    }

    /**
     * @var string $referralCode
     * @ORM\Column(type="string", unique=true)
     */
    private string $referralCode;

    /**
     * @param string $referralCode
     * @return self
     */
    public function setReferralCode(string $referralCode): self
    {
        $this->referralCode = $referralCode;
        return $this;
    }

    /**
     * @return string
     */
    public function getReferralCode(): string
    {
        return $this->referralCode;
    }

    /**
     * @var AppUser|null
     * @ORM\ManyToOne(targetEntity="AppUser")
     * @ORM\JoinColumn(name="referrer_id", referencedColumnName="id", onDelete="SET NULL")
     */
    private ?AppUser $referrer;

    /**
     * @param AppUser|null $referrer
     * @return self
     */
    public function setReferrer(?AppUser $referrer): self
    {
        $this->referrer = $referrer;
        return $this;
    }

    /**
     * @return AppUser|null
     */
    public function getReferrer(): ?AppUser
    {
        return $this->referrer;
    }

    /**
     * @ORM\Column(type="boolean", name="is_admin", options={"default": false})
     * @var bool $admin
     */
    private bool $admin = false;

    /**
     * @param bool $admin
     * @return $this
     */
    public function setAdmin(bool $admin) : self
    {
        if(!$this->isDeveloper()) $this->admin = $admin;
        else $this->admin = true;
        return $this;
    }

    /**
     * @return bool
     */
    public function isAdmin() : bool
    {
        return $this->admin;
    }

    /**
     * @var bool $developer
     * @ORM\Column(type="boolean", name="is_developer", options={"default": false})
     */
    private bool $developer = false;

    /**
     * @return bool
     */
    public function isDeveloper() : bool
    {
        return $this->developer;
    }

    /**
     * @param bool $developer
     * @return self
     */
    public function setDeveloper(bool $developer): self
    {
        $this->developer = $developer;
        return $this;
    }

    /**
     * @ORM\Column(type="datetime", options={"default": "9999-12-31"})
     * @var \DateTime $expireTime
     */
    private \DateTime $expireTime;

    /**
     * @param \DateTime $expireTime
     * @return self
     */
    public function setExpireTime(\DateTime $expireTime): self
    {
        if(!$this->isDeveloper()) $this->expireTime = $expireTime;
        else $this->setAsNeverExpireUser();
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getExpireTime(): \DateTime
    {
        return $this->expireTime;
    }

    /**
     * @var string|null $avatar
     * @ORM\Column(type="string", nullable=true)
     */
    private ?string $avatar = null;

    /**
     * @param string|null $avatar
     * @return self
     */
    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    /**
     * @return bool
     */
    public function isNeverExpireUser() : bool
    {
        return $this->expireTime->format("Y-m-d") === "9999-12-31";
    }

    /**
     * @return self
     */
    public function setAsNeverExpireUser() : self
    {
        $this->expireTime = new \DateTime("9999-12-31");
        return $this;
    }

    /**
     * @var bool
     */
    private bool $anonymous = false;

    /**
     * @return bool
     */
    public function isAnonymous() : bool
    {
        return $this->anonymous;
    }

    /**
     * @ORM\Column(type="datetime")
     * @var \DateTime $createAt
     */
    private \DateTime $createAt;

    /**
     * @return \DateTime|null
     */
    public function getCreateAt() : ?\DateTime
    {
        return $this->createAt;
    }

    /**
     * @ORM\PrePersist()
     * @return $this
     */
    public function setCreateAt() : self
    {
        $this->createAt = new \DateTime("now");
        return $this;
    }

    /**
     * @ORM\Column(type="datetime")
     * @var \DateTime
     */
    private \DateTime $updateAt;

    /**
     * @return \DateTime|null
     */
    public function getUpdateAt() : ?\DateTime
    {
        return $this->updateAt;
    }

    /**
     * @ORM\PreUpdate()
     * @ORM\PrePersist()
     * @return $this
     */
    public function setUpdateAt() : self
    {
        $this->updateAt = new \DateTime("now");
        return $this;
    }

    public function getRoles()
    {
        if($this->anonymous) return array("ROLE_ANONYMOUS");

        $roles = array();
        if($this->developer) $roles[] = "ROLE_DEVELOPER";
        if($this->admin) $roles[] = "ROLE_ADMIN";
        $roles[] = "ROLE_USER";

        return $roles;
    }

    /**

src/Controller/App/Admin/Banner/CreateController.php
<?php

namespace App\Controller\App\Admin\Banner;

use App\Form\App\Admin\Banner\CreateType;
use App\Service\Entity\Banner\CreateService;
use App\Service\Entity\Banner\Exception\NameRequiredException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CreateController extends AbstractController
{
    /**
     * @param Request $request
     * @param CreateService $createService
     * @return Response
     * @Route("/admin/banners/create", name="app.admin.banners.create")
     */
    public function __invoke(Request $request, CreateService $createService): Response
    {
        $this->denyAccessUnlessGranted("ROLE_ADMIN");

        $data = array();
        $bannerCreateForm = $this->createForm(CreateType::class, $data);
        $bannerCreateForm->handleRequest($request);

        if($bannerCreateForm->isSubmitted() && $bannerCreateForm->isValid())
        {
            $data = $bannerCreateForm->getData();

            try {
                $createResult = $createService->create($data);

                return $this->redirectToRoute("app.admin.banners.fetch", array(
                    "uuid" => $createResult->getBanner()->getUuid()
                ));
            } catch (NameRequiredException $nameRequiredException) {
                $bannerCreateForm->addError(new FormError("Banner 名稱不得為空。"));
            }
        }

        return $this->render('app/admin/banner/create/index.html.twig', array(
            "bannerCreateForm" => $bannerCreateForm->createView()
        ));
    }
}

src/Controller/App/Admin/BannerItem/CreateController.php
<?php

namespace App\Controller\App\Admin\BannerItem;

use App\Entity\Banner;
use App\Form\App\Admin\BannerItem\CreateType;
use App\Repository\BannerRepository;
use App\Service\Entity\BannerItem\CreateService;
use App\Service\Entity\BannerItem\Exception\ImageRequiredException;
use App\Service\Entity\BannerItem\Result\CreateResult;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CreateController extends AbstractController
{
    /**
     * @param Request $request
     * @param string $uuid
     * @param CreateService $createService
     * @return Response
     * @Route("/admin/banners/{uuid}/items/create", name="app.admin.banner_items.create")
     */
    public function __invoke(Request $request, string $uuid, CreateService $createService): Response
    {
        $this->denyAccessUnlessGranted("ROLE_ADMIN");

        $entityManager = $this->getDoctrine()->getManager();

        /**
         * @var BannerRepository $bannerRepository
         */
        $bannerRepository = $entityManager->getRepository(Banner::class);
        $banner = $bannerRepository->findOneByUuid($uuid);

        if(!$banner)
            return $this->redirectToRoute("app.admin.banners.list");

        $data = array();
        $bannerItemCreateForm = $this->createForm(CreateType::class, $data);
        $bannerItemCreateForm->handleRequest($request);

        if($bannerItemCreateForm->isSubmitted() && $bannerItemCreateForm->isValid()) {

            $data = $bannerItemCreateForm->getData();

            try {
                $createResult = $createService->create($banner, $data);
                return $this->redirectToRoute("app.admin.banners.fetch", array(
                    "uuid" => $banner->getUuid()
                ));
            } catch (ImageRequiredException $imageRequiredException) {
                $bannerItemCreateForm->addError(new FormError("圖片是必要欄位"));
            }

        }

        return $this->render('app/admin/banner-item/create/index.html.twig', array(
            "bannerItemCreateForm" => $bannerItemCreateForm->createView(),
            "banner" => $banner
        ));
    }
}

src/Controller/App/Admin/Service/CreateController.php
<?php

namespace App\Controller\App\Admin\Service;

use App\Entity\Service;
use App\Form\App\Admin\Service\CreateType;
use App\Service\Entity\Service\CreateService;
use App\Service\Entity\Service\Exception\NameRequiredException;
use App\Service\Entity\Service\Result\CreateResult;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CreateController extends AbstractController
{
    /**
     * @param Request $request
     * @param CreateService $createService
     * @return Response
     * @Route("/admin/services/create", name="app.admin.services.create")
     */
    public function __invoke(Request $request,
                             CreateService $createService): Response
    {
        $this->denyAccessUnlessGranted("ROLE_ADMIN");

        $data = array();
        $serviceCreateForm = $this->createForm(CreateType::class, $data);
        $serviceCreateForm->handleRequest($request);

        if($serviceCreateForm->isSubmitted() && $serviceCreateForm->isValid()) {

            $data = $serviceCreateForm->getData();

            try {
                $createResult = $createService->create($data);
                $service = $createResult->getService();

                return $this->render("app/admin/service/create/finished.html.twig", array(
                    "service" => $service,
                    "plainToken" => $createResult->getPlainToken()
                ));
            } catch (NameRequiredException $nameRequiredException) {
                $serviceCreateForm->addError(new FormError("服務名稱不得為空"));
            }

        }

        return $this->render('app/admin/service/create/index.html.twig', array(
            "serviceCreateForm" => $serviceCreateForm->createView()
        ));
    }
}

src/Controller/App/Admin/User/DeleteController.php
<?php

namespace App\Controller\App\Admin\User;

use App\Entity\AppUser;
use App\Repository\AppUserRepository;
use App\Security\Voter\AppUserVoter;
use App\Service\Entity\AppUser\DeleteService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DeleteController extends AbstractController
{
    /**
     * @param Request $request
     * @param string $uuid
     * @param DeleteService $deleteService
     * @return Response
     * @Route("/admin/users/{uuid}/delete", name="app.admin.users.delete")
     */
    public function __invoke(Request $request, string $uuid, DeleteService $deleteService): Response
    {
        $this->denyAccessUnlessGranted("ROLE_ADMIN");

        $entityManager = $this->getDoctrine()->getManager();

        /**
         * @var AppUserRepository $appUserRepository
         */
        $appUserRepository = $entityManager->getRepository(AppUser::class);
        $appUser = $appUserRepository->findOneByUuid($uuid);

        $this->denyAccessUnlessGranted(AppUserVoter::APP_USER_DELETE, $appUser);

        if($appUser) {
            $deleteService->delete($appUser);
        }

        return $this->redirectToRoute("app.admin.users.list");
    }
}

templates/app/admin/user/create/index.html.twig
{% extends "app/admin/base.html.twig" %}

{% block title %}新增用戶{% endblock %}

{% block breadcrumb %}
    <div class="page-header-breadcrumb">
        <ul class="breadcrumb-title">
            <li class="breadcrumb-item" style="float: left;">
                <a href="/admin"> <i class="feather icon-home"></i> </a>
            </li>
            <li class="breadcrumb-item" style="float: left;">
                <a href="{{ url('app.admin.users.list') }}"> 管理使用者 </a>
            </li>
            <li class="breadcrumb-item" style="float: left;">
                <a href="javascript:void(0)"> 新增用戶 </a>
            </li>
        </ul>
    </div>
{% endblock %}

{% block user_menu %}pcoded-trigger{% endblock %}
{% block user_create_menu %}active pcoded-trigger{% endblock %}

{% block content_title %}新增用戶{% endblock %}
{% block content_description %}新增一個網站用戶，並賦予用戶相對應的權限{% endblock %}


{% block body %}
    <!-- Page-body start -->
    <div class="page-body">
        <!-- Row start -->
        <div class="row">
            <!-- Multiple Open Accordion start -->
            <div class="col-xl-9 col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-header-text">新增用戶</h5>
                    </div>
                    <div class="card-block">
                        {{ form_start(appUserCreateForm) }}
                        {% if form_errors(appUserCreateForm) %}
                        <div class="alert alert-danger background-danger">
                            {{ form_errors(appUserCreateForm) }}
                        </div>
                        {% endif %}
                        <div class="row">
                            <div class="col-12">
                                <div id="uploader"
                                     data-controller="uploader"
                                     data-uploader-title-value="拖曳或點選這裡，上傳用戶頭像。"
                                     data-uploader-output-value="create_avatar"
                                     data-uploader-image-value=""></div>
                            </div>
                        </div>
                        <div class="form-group row">
                            {{ form_label(appUserCreateForm.email, '電子郵件', {'label_attr': {'class': 'col-lg-3 col-xl-2 col-form-label'}}) }}
                            <div class="col-lg-9 col-xl-10">
                                {{ form_widget(appUserCreateForm.email, {'attr': {'class': 'form-control', 'autocomplete': 'off'}}) }}
                            </div>
                        </div>
                        <div class="form-group row">
                            {{ form_label(appUserCreateForm.mobile, '手機號碼', {'label_attr': {'class': 'col-lg-3 col-xl-2 col-form-label'}}) }}
                            <div class="col-lg-9 col-xl-10">
                                {{ form_widget(appUserCreateForm.mobile, {'attr': {'class': 'form-control', 'autocomplete': 'off'}}) }}
                            </div>
                        </div>
                        <div class="form-group row">
                            {{ form_label(appUserCreateForm.password, '密碼', {'label_attr': {'class': 'col-lg-3 col-xl-2 col-form-label'}}) }}
                            <div class="col-lg-9 col-xl-10">
                                {{ form_widget(appUserCreateForm.password, {'attr': {'class': 'form-control', 'autocomplete': 'off'}}) }}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="create_expire_time" class="col-lg-3 col-xl-2 col-form-label">
                                帳號過期時間
                                <i class="fa fa-question-circle" data-toggle="tooltip" data-placement="right"
                                   data-original-title="這裡的用戶到期時間是指，該用戶到達此設定的時間的瞬間將被強制登出並且無法執行任何需要用戶權限的動作。因此你也可以透過將某用戶設為過期來凍結該用戶並且強制登出的該用戶的所有裝置。"></i>
                            </label>
                            <div class="col-lg-9 col-xl-10">
                                {{ form_widget(appUserCreateForm.expire_time, {'attr': {'class': 'form-control', 'autocomplete': 'off', "type": "date"}}) }}
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-lg-3 col-xl-2"></div>
                            <div class="col-lg-9 col-xl-10">
                                <div class="checkbox-color checkbox-primary">
                                    {{ form_widget(appUserCreateForm.forever) }}
                                    {{ form_label(appUserCreateForm.forever) }}
                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-lg-3 col-xl-2"></div>
                            <div class="col-lg-9 col-xl-10">
                                <div class="checkbox-color checkbox-primary">
                                    {{ form_widget(appUserCreateForm.is_admin) }}
                                    {{ form_label(appUserCreateForm.is_admin) }}
                                </div>
                            </div>
                        </div>
                        {{ form_widget(appUserCreateForm.avatar, {'attr': {'class': 'd-none'}}) }}
                        <div class="row">
                            <div class="col-lg-3 col-xl-2"></div>
                            <div class="col-lg-9 col-xl-10">
                                <button class="btn btn-primary">新增使用者</button>
                            </div>
                        </div>
                        {{ form_end(appUserCreateForm) }}
                    </div>
                </div>
            </div>
            <!-- Multiple Open Accordion ends -->
        </div>
        <!-- Row end -->
    </div>
    <!-- Page-body end -->
{% endblock %}

{% block javascripts %}
    <script>
        $('#create_forever').click(function() {
            $('#create_expire_time').attr("disabled", $(this).is(":checked"));
        })
    </script>
{% endblock %}